name: ExoticGarden+
version: 0.1.0
load: STARTUP
author: springfoxteam
authors: [springfoxteam, TheBusyBiscuit]
main: org.bukkit.plugin.ExoticGardenPlus
depend: [CSCore-Lib, Slimefun, ExoticGarden]
softdepend: [CSCore-Lib, Slimefun]
website: https://dev.bukkit.org/projects/exoticgarden-unofficial
